kind: Deployment
apiVersion: apps/v1
metadata:
  name: update-status
  namespace: microservice
  labels:
    app.kubernetes.io/name: update-status
    app.kubernetes.io/part-of: update-status
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: update-status
  template:
    metadata:
      labels:
        app.kubernetes.io/name: update-status
        app.kubernetes.io/part-of: update-status
    spec:
      containers:
        - name: update-status
          image: wonyus/update-status:latest
          imagePullPolicy: Always
          resources:
            limits:
              cpu: "1"
              memory: 256Mi
            requests:
              cpu: "0.5"
              memory: 256Mi
          env:
            - name: DB_PG_URL
              valueFrom:
                configMapKeyRef:
                  name: update-status-config
                  key: DB_PG_URL
            - name: MQTT_BROKER_PORT
              valueFrom:
                configMapKeyRef:
                  name: update-status-config
                  key: MQTT_BROKER_PORT
            - name: MQTT_BROKER_URL
              valueFrom:
                configMapKeyRef:
                  name: update-status-config
                  key: MQTT_BROKER_URL
            - name: MQTT_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: update-status-config
                  key: MQTT_USERNAME
            - name: MQTT_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: update-status-config
                  key: MQTT_PASSWORD
            - name: MQTT_CLIENT_ID
              valueFrom:
                configMapKeyRef:
                  name: update-status-config
                  key: MQTT_CLIENT_ID
            - name: MQTT_TOPIC
              valueFrom:
                configMapKeyRef:
                  name: update-status-config
                  key: MQTT_TOPIC
