version: "3.7"
services:
  update-status-service:
    image: wonyus/update-status:latest
    container_name: update-status-service
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - .:/app