service: update-status-service

provider:
  name: aws
  runtime: go1.x
  region: ap-southeast-1
  stage: v1

package:
  patterns:
    - "!./**"
    - ./bin/**

functions:
  main:
    handler: bin/main # route to binary
    url: true
    events:
      - http:
          path: /{proxy+}
          method: any
    environment:
      GIN_MODE: release
