name: build backend

on:
  push:
    branches: ["main"]

jobs:
  docker:
    runs-on: ubuntu-latest
 
    steps:
      - id: commit
        uses: pr-mpt/actions-commit-hash@v2

      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Fetch tags
        run: git fetch --depth=1 --tags
      
      - name: Get last tag
        run: echo "Last tag is $(git describe --tags --abbrev=0)"
        id: get_last_tag
        env:
          LAST_TAG: ${{ steps.get_last_tag.outputs.stdout }}

      - name: Use last tag in subsequent steps
        run: echo "Last tag is $LAST_TAG"
        
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: wonyus/update-status:latest, wonyus/update-status:${{  env.LAST_TAG }}